services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:handler --host 0.0.0.0 --port 10000
    envVars:
      - key: ENV_VAR_NAME
        value: "value"
